FROM python:3.8.9-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
    
CMD [ "python3", "bot_service.py"]
