version: "3"

services:
  bot_service:
    depends_on: 
      - influxdb
    build:
      context: .
      dockerfile: ./Dockerfile.bot
    env_file:
    - ./.env
    volumes:
      - /etc/logs:/app/logs
      
  telegram_notification_service:
    build:
      context: .
      dockerfile: ./Dockerfile.telegram_notification_service
    env_file:
    - ./.env
    volumes:
      - /etc/logs:/app/logs

  worker_service:
    build:
      context: .
      dockerfile: ./Dockerfile.worker_service
    env_file:
    - ./.env
    volumes:
      - /etc/logs:/app/logs
    
  
  broadcast_service:
    build:
      context: .
      dockerfile: ./Dockerfile.broadcast_service
    env_file:
    - ./.env
    volumes:
      - /etc/logs:/app/logs

  payouts_service:
    build:
      context: .
      dockerfile: ./Dockerfile.payouts_service
    env_file:
    - ./.env
    volumes:
      - /etc/logs:/app/logs
    
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    env_file:
    - ./.env
    ports:
      - "3029:3029"
    expose:
      - "3029"
    volumes:
      - /etc/logs:/app/logs

  influxdb:
    image: influxdb:1.8-alpine
    container_name: "test-stats-influxdb"
    restart: always
    volumes:
      - "influxdb:/var/lib/influxdb"
    env_file:
      - ./.env

  grafana:
    image: grafana/grafana:7.3.4
    container_name: "test-stats-grafana"
    volumes:
      - "grafana-data:/var/lib/grafana"
    environment:
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE=browser
    ports:
      - "${GRAFANA_PORT}:3000"

volumes:
  influxdb:
  grafana-data: