FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
    
CMD [ "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "3029"]
