version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile.bot
    env_file:
    - ./.env
      
  service:
    build:
      context: .
      dockerfile: ./Dockerfile.service
    env_file:
    - ./.env
