FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
    
CMD [ "python3", "bot.py"]