version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile.bot
    env_file:
    - ./.env
    volumes:
      - ./logs:/home/logs
      
  service:
    build:
      context: .
      dockerfile: ./Dockerfile.service
    env_file:
    - ./.env
    volumes:
      - ./logs:/home/logs

    
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    env_file:
    - ./.env
    ports:
      - "3029:3029"
    expose:
      - "3029"
    volumes:
      - ./logs:/home/logs
