version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile.bot
    env_file:
    - ./.env
      
  service:
    build:
      context: .
      dockerfile: ./Dockerfile.service
    env_file:
    - ./.env

    
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    env_file:
    - ./.env
    ports:
      - "3000:3000"
    expose:
      - "3000"
