/*
 Navicat Premium Data Transfer

 Source Server         : my_12
 Source Server Type    : PostgreSQL
 Source Server Version : 120005
 Source Host           : 194.99.21.140:5433
 Source Catalog        : Emcd
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120005
 File Encoding         : 65001

 Date: 02/03/2021 21:13:12
*/


-- ----------------------------
-- Sequence structure for account_coin_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."account_coin_id_seq";
CREATE SEQUENCE "public"."account_coin_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for question_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."question_id_seq";
CREATE SEQUENCE "public"."question_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for account
-- ----------------------------
DROP TABLE IF EXISTS "public"."account";
CREATE TABLE "public"."account" (
  "user_id" int8 NOT NULL,
  "account_id" uuid NOT NULL,
  "username" text COLLATE "pg_catalog"."default" NOT NULL,
  "create_datetime" timestamp(6),
  "modified_datetime" timestamp(6)
)
;

-- ----------------------------
-- Table structure for account_coin
-- ----------------------------
DROP TABLE IF EXISTS "public"."account_coin";
CREATE TABLE "public"."account_coin" (
  "id" int4 NOT NULL DEFAULT nextval('account_coin_id_seq'::regclass),
  "account_id" uuid NOT NULL,
  "coin_id" text COLLATE "pg_catalog"."default" NOT NULL,
  "address" text COLLATE "pg_catalog"."default",
  "total_count" int4 NOT NULL,
  "active_count" int4 NOT NULL,
  "inactive_count" int4 NOT NULL,
  "dead_count" int4 NOT NULL,
  "total_hashrate" int8 NOT NULL,
  "total_hashrate1h" int8 NOT NULL,
  "total_hashrate24h" int8 NOT NULL,
  "last_update_datetime" timestamp(6) NOT NULL,
  "is_active" bool NOT NULL,
  "user_id" int8 NOT NULL
)
;

-- ----------------------------
-- Table structure for account_coin_notification
-- ----------------------------
DROP TABLE IF EXISTS "public"."account_coin_notification";
CREATE TABLE "public"."account_coin_notification" (
  "account_coin_id" int4 NOT NULL,
  "is_enabled" bool NOT NULL DEFAULT true
)
;

-- ----------------------------
-- Records of account_coin_notification
-- ----------------------------

-- ----------------------------
-- Table structure for lang
-- ----------------------------
DROP TABLE IF EXISTS "public"."lang";
CREATE TABLE "public"."lang" (
  "id" int4 NOT NULL,
  "name" text COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for question
-- ----------------------------
DROP TABLE IF EXISTS "public"."question";
CREATE TABLE "public"."question" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "created_date_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for question_answer_translation
-- ----------------------------
DROP TABLE IF EXISTS "public"."question_answer_translation";
CREATE TABLE "public"."question_answer_translation" (
  "question_id" int4 NOT NULL,
  "lang_id" int4 NOT NULL,
  "translation" text COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for question_translation
-- ----------------------------
DROP TABLE IF EXISTS "public"."question_translation";
CREATE TABLE "public"."question_translation" (
  "question_id" int4 NOT NULL,
  "lang_id" int4 NOT NULL,
  "translation" text COLLATE "pg_catalog"."default" NOT NULL
)
;

-- Table structure for role
-- ----------------------------
DROP TABLE IF EXISTS "public"."role";
CREATE TABLE "public"."role" (
  "id" int4 NOT NULL,
  "name" text COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS "public"."user";
CREATE TABLE "public"."user" (
  "id" int8 NOT NULL,
  "lang_id" int4 NOT NULL,
  "created_datetime" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "role_id" int4 NOT NULL DEFAULT 1
)
;

-- ----------------------------
-- Table structure for user_coin
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_coin";
CREATE TABLE "public"."user_coin" (
  "user_id" int4 NOT NULL,
  "coin_id" text COLLATE "pg_catalog"."default" NOT NULL,
  "is_enabled" bool NOT NULL DEFAULT true
)
;

-- ----------------------------
-- Table structure for user_notification
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_notification";
CREATE TABLE "public"."user_notification" (
  "user_id" int4 NOT NULL,
  "is_enabled" bool NOT NULL DEFAULT true
)
;
-- ----------------------------
-- Table structure for worker_account_history
-- ----------------------------
DROP TABLE IF EXISTS "public"."worker_account_history";
CREATE TABLE "public"."worker_account_history" (
  "account_coin_id" int4 NOT NULL,
  "worker_id" text COLLATE "pg_catalog"."default" NOT NULL,
  "stored_datetime" timestamp(6) NOT NULL,
  "status_id" int4 NOT NULL,
  "hashrate" int8 NOT NULL,
  "hashrate1h" int8 NOT NULL,
  "hashrate24h" int8 NOT NULL,
  "reject" float8 NOT NULL
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."account_coin_id_seq"
OWNED BY "public"."account_coin"."id";
SELECT setval('"public"."account_coin_id_seq"', 428, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."question_id_seq"
OWNED BY "public"."question"."id";
SELECT setval('"public"."question_id_seq"', 7, true);

-- ----------------------------
-- Primary Key structure for table account
-- ----------------------------
ALTER TABLE "public"."account" ADD CONSTRAINT "account_pkey" PRIMARY KEY ("user_id", "account_id");

-- ----------------------------
-- Primary Key structure for table account_coin
-- ----------------------------
ALTER TABLE "public"."account_coin" ADD CONSTRAINT "account_coin_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table account_coin_notification
-- ----------------------------
ALTER TABLE "public"."account_coin_notification" ADD CONSTRAINT "account_coin_notification_pkey" PRIMARY KEY ("account_coin_id");

-- ----------------------------
-- Primary Key structure for table lang
-- ----------------------------
ALTER TABLE "public"."lang" ADD CONSTRAINT "lang_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table question
-- ----------------------------
ALTER TABLE "public"."question" ADD CONSTRAINT "question_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table role
-- ----------------------------
ALTER TABLE "public"."role" ADD CONSTRAINT "role_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table user
-- ----------------------------
ALTER TABLE "public"."user" ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table user_coin
-- ----------------------------
ALTER TABLE "public"."user_coin" ADD CONSTRAINT "user_coin_pkey" PRIMARY KEY ("user_id", "coin_id");

-- ----------------------------
-- Primary Key structure for table user_notification
-- ----------------------------
ALTER TABLE "public"."user_notification" ADD CONSTRAINT "user_notification_pkey" PRIMARY KEY ("user_id");

-- ----------------------------
-- Primary Key structure for table worker_account_history
-- ----------------------------
ALTER TABLE "public"."worker_account_history" ADD CONSTRAINT "worker_account_history_pkey" PRIMARY KEY ("account_coin_id", "worker_id", "stored_datetime");

-- ----------------------------
-- Foreign Keys structure for table account
-- ----------------------------
ALTER TABLE "public"."account" ADD CONSTRAINT "account_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table question_answer_translation
-- ----------------------------
ALTER TABLE "public"."question_answer_translation" ADD CONSTRAINT "question_answer_translation_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."question" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table question_translation
-- ----------------------------
ALTER TABLE "public"."question_translation" ADD CONSTRAINT "question_translation_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."question" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table user
-- ----------------------------
ALTER TABLE "public"."user" ADD CONSTRAINT "user_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
