name: Deploy Bot Dev

env:
  directoryName: 'Emcd.Bot.Development'

on:
  push:
    branches: 
      - 'master'
    paths-ignore:
      - 'webui/**'
  workflow_dispatch:


jobs:

  pass-envfile:
    environment: dev
    runs-on: ubuntu-18.04

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          envkey_TOKEN: ${{ secrets.TOKEN }}
          envkey_ENV_NAME: ${{ secrets.ENV_NAME }}
          envkey_POEDITOR_TOKEN: ${{ secrets.POEDITOR_TOKEN }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_POEDITOR_PROJECT_ID: ${{ secrets.POEDITOR_PROJECT_ID }}
          envkey_INFLUXDB_DB: ${{ secrets.INFLUXDB_DB }}
          envkey_INFUX_DB_HOST: ${{ secrets.INFUX_DB_HOST }}
          envkey_INFLUXDB_ADMIN_USER: ${{ secrets.INFLUXDB_ADMIN_USER }}
          envkey_INFLUXDB_ADMIN_USER_PASSWORD: ${{ secrets.INFLUXDB_ADMIN_USER_PASSWORD }}
          envkey_INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
          envkey_INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}
          envkey_INFLUXDB_HTTP_AUTH_ENABLED: ${{ secrets.INFLUXDB_HTTP_AUTH_ENABLED }}
          envkey_GRAFANA_PORT: ${{ secrets.GRAFANA_PORT }}
          envkey_INTERCOM_TOKEN: ${{ secrets.INTERCOM_TOKEN }}
          file_name: .env

      - name: Move envfile to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ".env"
          target: "${{env.directoryName}}/"

  deploy:
    needs: pass-envfile
    environment: dev
    runs-on: ubuntu-18.04

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout on host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd ${{env.directoryName}} && git submodule update --init --recursive && git fetch && git checkout ${{ steps.extract_branch.outputs.branch }} && git pull

      - name: Docker compose restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd ${{env.directoryName}} && docker-compose pull && docker-compose up -d --force-recreate --no-deps --build
